name: Mirror GitLab to GitHub

on:
  push:
    branches:
      - main

env:
  GIT_NAME: ${{ secrets.GIT_NAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fetch GitLab repository
      run: |
        git clone https://gitlab.com/spiritysdx/Oracle-server-keep-alive-script.git
        cd Oracle-server-keep-alive-script
        git checkout main
    
    - name: Configure Git
      run: |
        git config --global user.name "$GIT_NAME"
        git config --global user.email "$GIT_EMAIL"
    
    - name: Add GitHub Remote
      run: |
        git remote remove origin
        git remote add origin https://github.com/spiritLHLS/Oracle-server-keep-alive-script.git
    
    - name: Push to GitHub
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: main
        force: true
