name: Mirror GitLab repository to GitHub
on:
  push:
    branches:
      - main
env:
  GIT_NAME: ${{ secrets.GIT_NAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.name "${GIT_NAME}"
        git config --global user.email "${GIT_EMAIL}"
    - name: Add GitLab remote
      run: |
        git remote add gitlab https://gitlab.com/spiritysdx/Oracle-server-keep-alive-script
    - name: Fetch from GitLab
      run: |
        git fetch gitlab main
    - name: Push to GitHub
      run: |
        git push origin main
